### ISSUE TITLE
Template for UrBackup, should I update or add new version?

### ISSUE THREAD

**Issue by DoTheEvo** [portainer/templates#100]
currently the template points to [cfstras/urbackup](https://hub.docker.com/r/cfstras/urbackup) image.

The issues.

- there is alternative official image - [uroni/urbackup-server](https://hub.docker.com/r/uroni/urbackup-server). Though not marked official, its the same nick as [the actual guy](https://github.com/uroni) behind the project
- its more up to date
- the current one is 9 months old, does not have network client discovery working at it uses wrong udp port and is left isoleted, or btrfs support, or ports for web interface are left at random instead of what documentation means

I am wondering, if I make pull request, should I [edit the existing one](https://github.com/DoTheEvo/templates/commit/1d30cc68b44a81a72c1ebeea65ad60d58d219856) to be better, or should I add another new urbackup?

**Comment by deviantony** [comment]
Hey @DoTheEvo we're removed the UrBackup template for now because the original image was unmaintained.

Happy to bring it back if folks are looking for it.
