### ISSUE TITLE
MySQL Template — No such image: mysql:latest

### ISSUE THREAD

**Issue by maxiride** [portainer/templates#108]
I tried to isntall MySQL fromt he provided App Template without success which is weird since as per MySQL Docker Hub image MySQL 8 supported tags are "8.0.16, 8.0, 8, latest (8.0/Dockerfile)"

Error: No such image: mysql:latest
Screenshot: https://i.imgur.com/wbwPFNZ.png

**Comment by tricoos** [comment]
Same here. EVen "mariadb:10" resulted in the same error though I could pull the image "mariadb:latest" manually under "images"

**Comment by sibtcha** [comment]
Same too. With MariaDB and with MySQL

**Comment by CurtisFeatures** [comment]
A bit late to the party but thought i would chip in. I had this issue and solved by changing the template image to be: 
mariadb/server:10.4
or
mariadb/server:latest

**Comment by deviantony** [comment]
I don't think this is an issue anymore.
I've been able to successfully deploy MariaDB and MySQL using the templates and they both work fine.

Closing for now, happy to re-open if we're still having issues.
