### ISSUE TITLE
Template category

### ISSUE THREAD

**Issue by deviantony** [portainer/templates#33]
Each template should define a category (database, web server, developer tool...) so they could be sorted in the Portainer UI.

**Comment by euskadi31** [comment]
Hi,

Takes an example on the Gentoo Linux package system ;)

templates/`category`/`template-name`.json

Ex: `templates/www-servers/nginx.json`

see: https://packages.gentoo.org/

**Comment by deviantony** [comment]
Categories have been added via https://github.com/portainer/templates/commit/487f3c08b232b5df534df845b49be6a56aeeb3e1
