### ISSUE TITLE
Glusterfs

### ISSUE THREAD

**Issue by sonaht** [portainer/templates#34]
Hi

I would suggest a new template that will add a glusterfs HA distributed storage volume system.

That coupled with the swarm mode will create a seriously HA infrastructure since data/volumes will be HA as well.

**Comment by cloudinovasi** [comment]
Do you have a suggested docker hub image that could be used? Portainer dont actually create the templates, only currate them..

**Comment by deviantony** [comment]
@sonaht as posted by @cloudinovasi we only curate existing Dockerhub images at the moment.

**Comment by sonaht** [comment]
Ok @deviantony I understand.

My point is beyond the simple template inclusion of a glusterfs cluster.

I am proposing the actual inclusion of glusterfs in portainer, in order to provide HA storage the same way that swarm offers global containers. 

It is great to have global containers, or containers that can be / are migrated from host to host, but the storage (data volumes) are not highly available. 

If that is an option to be considered then ok, but it is what I meant from the beginning.

**Comment by deviantony** [comment]
Oh right, this is definitely not in the scope of the templates ! At the moment, Portainer is designed to be an administration panel for Docker and not an orchestration/platform solution. This may come later on though...
