### ISSUE TITLE
LinuxServer.io template contributions

### ISSUE THREAD

**Issue by IronicBadger** [portainer/templates#35]
Hi,

I'm one of the LinuxServer.io guys, we make 'a few' Docker containers [here](http://tools.linuxserver.io/dockers). We maintain a bunch of templates for native integration into unRAID and OpenMediaVault already. I've been using your UI for a couple of weeks and really like it.

We'd like to know if you're interested in starting a partnership to include our templates in your UI out of the box?

Regards.
IB

**Comment by ncresswell** [comment]
Yes, we are more than happy. Please join our slack channel so we can discuss in more detail.

**Comment by IronicBadger** [comment]
Great! You'll have to send me an invite I think... 

alexktz at g mail

**Comment by IronicBadger** [comment]
Getting an error signing up for your Slack page as are my ls.io compadres.

**Comment by IronicBadger** [comment]
![screenshot from 2016-11-05 21-33-07](https://cloud.githubusercontent.com/assets/2773080/20033723/7f266c0e-a39f-11e6-990d-093e724e7b16.png)

**Comment by deviantony** [comment]
@IronicBadger I'll fix that soon, I will tell you when it's ready here.

**Comment by deviantony** [comment]
@IronicBadger should be fixed now :)

See you on Slack !

**Comment by Fish2** [comment]
any new on when LinuxServer.io will be coming to templates ?

**Comment by deviantony** [comment]
No news from LinuxServer since. ping @IronicBadger

**Comment by j0nnymoe** [comment]
Once there has been some changes made to the templates, we can look into getting something together for portainer :) ( ref: https://github.com/portainer/templates/issues/44 )

**Comment by RXWatcher1** [comment]
@IronicBadger @j0nnymoe 

This looks like it's resolved. I'd really like to see your docker containers in Portainer.
Is there anything else you need? time? :) 

Thanks for all of your efforts with linuxserver.io..you guys rock!
