### ISSUE TITLE
multiple architecture support

### ISSUE THREAD

**Issue by vielmetti** [portainer/templates#47]
Support templates that properly handle portainer running on architectures other than amd64. 

I'm not sure how this actually gets implemented in the future. In practice, if you are on a linux/arm64 machine, portainer presents you with linux/amd64 images as templates that won't run.

One possibility is another field in the template definition that describes the architectures it runs on; the bigger future is for widespread use of `multiarch` containers and some run-time check to validate for each container which architecture it is built for.

**Comment by vielmetti** [comment]
And an update:

Docker now has "multiarch" images, that run properly independent of the architecture you are on, by providing the correct image to the system based on its type. As of this writing, about 44 of the top 140 official packages on Docker Hub support multiarch.

I did an audit (using Phil Estes @estesp tool `mquery`) and currently 17/33 of the Portainer templates support multiarch, and of those 9/17 have arm64 versions. This means that on arm64, 9/33 templates "just work", and some others fail mysteriously, and others fail properly.

This is tremendous progress, and there's likely to be more forward progress when the official Alpine container has multiarch support, a task that's being worked on at https://github.com/gliderlabs/docker-alpine/issues/304 .

**Comment by deviantony** [comment]
Closing this one as most of the container images now support multi-arch and this is actually defined at image build time.
