### ISSUE TITLE
Add missing volume declarations

### ISSUE THREAD

**Issue by MiniDigger** [portainer/templates#48]
I just noticed that portainer was not showing any linked volumes for some of my containers and with the help of @ncresswell I was able to find that it just created a non persistent volume (the one auto generated by docker) and not a persistent one.
It is probably a good idea to add the volumes to some templates (I only played with wordpress, nginx and apache) as a user will most likely not expect that the volume gets deleted when the container gets deleted.

**Comment by deviantony** [comment]
@MiniDigger I will try to go around all the templates and fix that. Would you mind opening a PR with the added volumes for the templates you mentioned? I can see that `wordpress` expose a volume in its Dockerfile for example (https://github.com/docker-library/wordpress/blob/b807f1285869a220a5f72b935901603e5bde8822/php5.6/apache/Dockerfile#L30) is this the only volume declaration that should be added?

**Comment by MiniDigger** [comment]
I have no idea. I can try going thru all the templates and see if they expose volumes and create a pr later.

On Mar 2, 2017 09:52, Anthony Lapenna <notifications@github.com> wrote:

@MiniDigger<https://github.com/MiniDigger> I will try to go around all the templates and fix that. Would you mind opening a PR with the added volumes for the templates you mentioned? I can see that wordpress expose a volume in its Dockerfile for example (https://github.com/docker-library/wordpress/blob/b807f1285869a220a5f72b935901603e5bde8822/php5.6/apache/Dockerfile#L30) is this the only volume declaration that should be added?
