### ISSUE TITLE
Support foreground flags (i.e. -i -t) in portainer templates

### ISSUE THREAD

**Issue by JF1297** [portainer/templates#59]
**Feature Request:**  support foreground flags, i.e. (-i -t), in portainer templates

**Reference**:  This feature request is in reference to the screencast I just shared with you showing how foreground flag support is necessary in order to use a custom Portainer template to open a [python, etc] container (and keep it open).

**Link to screencast**: https://portainer.slack.com/files/forman/F53M0TW03/portainer-screencase.mov

_BTW_: love this software product (portainer) !

Thanks,

James

**Comment by deviantony** [comment]
Moved to https://github.com/portainer/portainer/issues/819
