### ISSUE TITLE
microsoft/mssql-server-linux:latest is outdated

### ISSUE THREAD

**Issue by jOphey** [portainer/templates#73]
MS decided to remove the :latest-tag:
https://hub.docker.com/r/microsoft/mssql-server-linux/

Please update the template to use tag :2017-GA

Thank you!

**Comment by deviantony** [comment]
Thanks for the report @jOphey 

Mind opening a PR ?

**Comment by jOphey** [comment]
Sure!
Here you go:
https://github.com/portainer/templates/pull/74

have a nice day!

**Comment by deviantony** [comment]
Closed by #74
