### ISSUE TITLE
MSSQL for windows

### ISSUE THREAD

**Issue by alexivkin** [portainer/templates#81]
There is no such thing as microsoft/mssql-server-windows:latest, only express and developer

https://hub.docker.com/r/microsoft/

**Comment by deviantony** [comment]
That's a good catch, thanks for the report @alexivkin ! Must have been replaced, we need to update our feed. Care to open a PR?

**Comment by alexivkin** [comment]
Done. #82

**Comment by deviantony** [comment]
Closed by #82
