### ISSUE TITLE
Can't edit IronFunctions' stack

### ISSUE THREAD

**Issue by steevegldev** [portainer/templates#88]
I deployed IronFunction from App Templates without any issue. But when I try to edit the stack and click on "Update the stack" button in Portainer, the page refresh and my changes are not present.

In Portainer's data folder I saw the IronFunction stack folder. In that folder, my changes has been push in a docker-compose.yml file.

So, not error and no change. Nothing in Portainer's and docker's logs

**Comment by deviantony** [comment]
Hi @steevegldev 

This is a known bug that was found in the latest release, it has been fixed already, see https://github.com/portainer/portainer/issues/1723

You can use our unstable build via `portainer/portainer:develop` in the meantime.
