### ISSUE TITLE
Update Elasticsearch Template

### ISSUE THREAD

**Issue by ajpahl1008** [portainer/templates#96]
There are two changes that will enable Portainer to make use of newer versions.
1.) Change to Elastic's official repo:  docker.elastic.co/elasticsearch
2.) Drop the "latest" tag and use a version.  

**Recommended Change: templates.json**

```
 {
    "type": "container",
    "title": "Elasticsearch",
    "description": "Open-source search and analytics engine",
    "categories": ["database"],
    "platform": "linux",
     "logo": "https://portainer.io/images/logos/elasticsearch.png",
    "repository": "docker.elastic.co/elasticsearch"   <--HERE
    "image": "elasticsearch:6.3.2",  <--HERE
    "ports": [
      "9200/tcp",
      "9300/tcp"
    ],
    "volumes": ["/usr/share/elasticsearch/data"]
  }
```

**Comment by jeremydouglass** [comment]
To underscore, this is a broken template, not just an update.

The current elasticsearch template fails to install because it is pointed at "latest" and that tag on elasticsearch is no longer available from dockerhub.
